source 'https://rubygems.org'

gem 'rake'

gem 'foreman'

gem 'rack', '1.6.8'
gem 'rack-contrib', '1.4.0'

gem 'unicorn', '5.4.0'

gem "sinatra", '1.4.8'
gem "sinatra-param"
gem "json"
gem "sinatra-cross_origin"
gem 'selenium-webdriver', '2.53.4'
gem 'chromedriver-helper'
